server:
  port: 2222
spring:
  application:
    name: warehouse-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:mongo}:${MONGO_PASS:mongo}@${MONGO_HOST:localhost}:${MONGO_PORT:27016}/warehouse?authSource=admin